GET http://localhost:5000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMxOTI1NjIsImRhdGEiOnsidXNlcm5hbWUiOiJmYXJpZDk1ZyIsImlkIjoiNjVmMzQ1MzY3YmMwOTIyY2FjZTU2NWQ1In0sImlhdCI6MTcxMzE5MjUzMn0.j4BlZaH3qz5HjwSiWmPFOG3326797icbCSwKNpo5lcM

###

POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MWQ1YjE1N2JmNGQ1YmM4NDEzMmFhNyIsImlhdCI6MTcxMzM3ODAzMCwiZXhwIjoxNzEzMzgxNjMwfQ.2j9-vhYwVPYsYchHgSC5VweDCejzvSEW0yymQqjtpKM

{
    "title": "first test blog with user",
    "author": "Farid Guluzade",
    "url": "https://google.com",
    "likes": 30
}

###

DELETE http://localhost:5000/api/blogs/661d633b01bd02ac12957d22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjFkNWIwOTdiZjRkNWJjODQxMzJhYTUiLCJpYXQiOjE3MTMyMDE5MTcsImV4cCI6MTcxMzIwNTUxN30.Sl7GxkvExH1FA_rvm4wJdc6vE7HXskctcwrAVZDysCs

###

PUT http://localhost:5000/api/blogs/66201312370c811480b576b7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MWQ1YjE1N2JmNGQ1YmM4NDEzMmFhNyIsImlhdCI6MTcxMzM3ODAzMCwiZXhwIjoxNzEzMzgxNjMwfQ.2j9-vhYwVPYsYchHgSC5VweDCejzvSEW0yymQqjtpKM

{
    "likes": 13
}