POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: bearer 

{
    "title": "Post 2",
    "author": "Post 2 by farid95g",
    "url": "http://post2.com",
    "user": "63358ab7e201df5c56653401"
}